twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        ga_project_name: 'SmProject'

when@test:
    twig:
        strict_variables: true
